---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/fixtures/roles

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: centos-5.10
- name: centos-6.6
- name: centos-7.1
- name: fedora-19
- name: fedora-20
- name: fedora-21
- name: debian-7.9
- name: debian-8.2

suites:
  - name: default
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        minion:
          master: 127.0.0.1
          grains:
            quinoa: delicious
            stooges:
              - larry
              - curly
              - moe
    excludes:
      - fedora-19
  - name: minion
    run_list:
      - role[salt_minion]
    attributes:
      salt:
        minion:
          master: 127.0.0.1
          grains:
            quinoa: delicious
            stooges:
              - larry
              - curly
              - moe
    includes:
      - fedora-19
