---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/fixtures/cookbooks

platforms:
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        minion:
          master: localhost
