---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/fixtures/cookbooks

platforms:
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: centos-5.10
- name: centos-6.5
- name: centos-7.0
- name: fedora-20
- name: debian-7.4
- name: fedora-19

suites:
  - name: default
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        minion:
          master: 127.0.0.1
