---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: test/fixtures/roles

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-5.11
- name: centos-6.8
- name: centos-7.1
- name: fedora-21
- name: fedora-22
- name: fedora-23
- name: fedora-24
- name: debian-7.11
- name: debian-8.5

suites:
  - name: default
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        minion:
          master: 127.0.0.1
          config:
            grains:
              quinoa: delicious
              stooges:
                - larry
                - curly
                - moe
  - name: salt-api
    run_list:
      - role[salt_master]
      - role[salt_minion]
    attributes:
      salt:
        master:
          api:
            enable: true
        minion:
          master: 127.0.0.1
          config:
            grains:
              quinoa: delicious
              stooges:
                - larry
                - curly
                - moe
