language: ruby
rvm:
  - 2.0.0
  - 2.2.3
before_script:
  - bundle exec berks install
script:
  - bundle exec rubocop
  - bundle exec foodcritic -f any .
  - bundle exec rspec --color --format progress
